---
title: "Untitled"
author: "Adam"
date: "9/13/2021"
output: html_document
---

```{r}
library(stringr)
library(gtools)
library(ggplot2)
# aggregate basis time series peak sequences, parse, viz frequencies
```

```{r}
# derive all possible sequences of X length for this granularity
Seqs=permutations(n=8,r=6,repeats.allowed = F)
# adjust so 0 is included
Seqs=(Seqs-1)
# initialize cross-subject sequence count dataframe: one row for each possibility
seqCount=rep(0,dim(Seqs)[1])
# get Subj List, "Subjs" from DataVolPhenoRelations at the moment
# for each subj
for (p in 1:length(Subjs)){
subj=Subjs[p]
# For each task
tasks = c('rest','SST','nback','MID')

# but not really for each task, just for rest RN
for (i in 1){
  # peak sequence
  pSfn=paste0('/cbica/projects/abcdfnets/results/wave_output/',subj,'/',subj,'_',tasks[i],'_PeakSeq_Fi')
  if (file.exists(pSfn)){
  peakSeq=read.delim(pSfn,header=F)
  TRfn=paste0('/cbica/projects/abcdfnets/results/wave_output/',subj,'/',subj,'_',tasks[i],'_TRSeq_Fi')
  trSeq=read.delim(TRfn,header=F)
  # convert to string for string searching
  strungPeakSeqs<-toString(peakSeq)
  # clean out \n's
  strungPeakSeqs<-gsub('\n','',strungPeakSeqs)
  # counts sequences
  for (S in 1:dim(Seqs)[1]){
    InstanceCount=str_count(strungPeakSeqs,pattern=toString(Seqs[S,]))
    seqCount[S]=seqCount[S]+InstanceCount
  }
}
# end each task
}
# end each sub
}
seqCountDF<-data.frame(seqCount)
seqCountDF$Sequence=NULL
# insert actual sequences for plotting
for (S in 1:dim(Seqs)[1]){
  seqCountDF$Sequence[S]=paste0(toString(Seqs[S,]))
}
# replace with net names
seqCountDF$Sequence<-gsub('0','GS',seqCountDF$Sequence)
seqCountDF$Sequence<-gsub('1','Aud',seqCountDF$Sequence)
seqCountDF$Sequence<-gsub('2','Mot',seqCountDF$Sequence)
seqCountDF$Sequence<-gsub('3','Vis',seqCountDF$Sequence)
seqCountDF$Sequence<-gsub('4','DAN',seqCountDF$Sequence)
seqCountDF$Sequence<-gsub('5','VAN',seqCountDF$Sequence)
seqCountDF$Sequence<-gsub('6','FP',seqCountDF$Sequence)
seqCountDF$Sequence<-gsub('7','DM',seqCountDF$Sequence)

# convert to z's
seqCountDF$seqCount<-scale(seqCountDF$seqCount)

#for shorter sequence plotting
ggplot(seqCountDF)+geom_point(aes(Sequence,seqCount),size=5)+theme_minimal(base_size=15)+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#### for big plots (long sequences)
ggplot(seqCountDF[seqCountDF$seqCount>3,])+geom_point(aes(Sequence,seqCount),size=5)+theme_minimal(base_size=15)+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
# derive all possible sequences of X length for this coarse granularity
Seqs=permutations(n=4,r=4,repeats.allowed = F)
# adjust so 0 is included
Seqs=(Seqs-1)
# initialize cross-subject sequence count dataframe: one row for each possibility
seqCount=rep(0,dim(Seqs)[1])
# get Subj List, "Subjs" from DataVolPhenoRelations at the moment
# for each subj
for (p in 1:length(Subjs)){
subj=Subjs[p]
# For each task
tasks = c('rest','SST','nback','MID')

# but not really for each task, just for rest RN
for (i in 1){
  # peak sequence
  pSfn=paste0('/cbica/projects/abcdfnets/results/wave_output/',subj,'/',subj,'_',tasks[i],'_PeakSeq_Co')
  if (file.exists(pSfn)){
  peakSeq=read.delim(pSfn,header=F)
  TRfn=paste0('/cbica/projects/abcdfnets/results/wave_output/',subj,'/',subj,'_',tasks[i],'_TRSeq_Co')
  trSeq=read.delim(TRfn,header=F)
  # convert to string for string searching
  strungPeakSeqs<-toString(peakSeq)
  # clean out \n's
  strungPeakSeqs<-gsub('\n','',strungPeakSeqs)
  # counts sequences
  for (S in 1:dim(Seqs)[1]){
    InstanceCount=str_count(strungPeakSeqs,pattern=toString(Seqs[S,]))
    seqCount[S]=seqCount[S]+InstanceCount
  }
}
# end each task
}
# end each sub
}
seqCountDF<-data.frame(seqCount)
seqCountDF$Sequence=NULL
# insert actual sequences for plotting
for (S in 1:dim(Seqs)[1]){
  seqCountDF$Sequence[S]=paste0(toString(Seqs[S,]))
}

# convert to z's
seqCountDF$seqCount<-scale(seqCountDF$seqCount)

#for shorter sequence plotting
ggplot(seqCountDF)+geom_point(aes(Sequence,seqCount),size=5)+theme_minimal(base_size=15)+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#### for big plots (long sequences)
ggplot(seqCountDF[seqCountDF$seqCount>3,])+geom_point(aes(Sequence,seqCount),size=5)+theme_minimal(base_size=15)+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```