---
title: "DataVolPhenoRelations"
author: "Adam"
date: "8/25/2021"
output: html_document
---
```{r}
# read in file for final included TR count, saveout list of subjs failing 12 minute mark
subjLevel<-readRDS('/cbica/projects/abcdfnets/results/Subject-level_waves_60')
failing<-na.omit(unlist(subjLevel$ID[subjLevel$TRs_r<900]))
# just parsing out NAs manually here
failing<-failing[1:80]
# and same for passing
passing<-na.omit(unlist(subjLevel$ID[subjLevel$TRs_r>900]))
passing<-passing[1:93]
# convert to subjID
subjNames<-gsub("/cbica/projects/abcdfnets/results/wave_output/","",failing)
Subjs<-gsub("/cbica/projects/abcdfnets/results/wave_output/","",passing)
# delete failing from output files
for (i in 1:length(subjNames)){
  Subj=subjNames[i]
  rmcommand=paste0('rm -r -f  /cbica/projects/abcdfnets/results/wave_output/',Subj)
  system(rmcommand)
}
```

```{r}
# resting state
rest=read.csv('~/Downloads/rest-trthreshes.csv')
# convert last row to subjID
subjNames<-gsub("/gpfs/fs001/cbica/projects/abcdfnets/scripts/PWs/PWs/ThreshDirec/","",rest$output6)
subjNames<-gsub('_rest.mat','',subjNames)
rest$subjectkey<-gsub('sub-NDARINV','NDAR_INV',subjNames)

# nback
nback=read.csv('~/Downloads/nback-trthreshes.csv')
# convert last row to subjID
subjNames<-gsub("/gpfs/fs001/cbica/projects/abcdfnets/scripts/PWs/PWs/ThreshDirec/","",nback$output6)
subjNames<-gsub('_nback.mat','',subjNames)
nback$subjectkey<-gsub('sub-NDARINV','NDAR_INV',subjNames)

# MID
mid=read.csv('~/Downloads/mid-trthreshes.csv')
# convert last row to subjID
subjNames<-gsub("/gpfs/fs001/cbica/projects/abcdfnets/scripts/PWs/PWs/ThreshDirec/","",mid$output6)
subjNames<-gsub('_MID.mat','',subjNames)
mid$subjectkey<-gsub('sub-NDARINV','NDAR_INV',subjNames)

# sst
sst=read.csv('~/Downloads/sst-trthreshes.csv')
# convert last row to subjID
subjNames<-gsub("/gpfs/fs001/cbica/projects/abcdfnets/scripts/PWs/PWs/ThreshDirec/","",sst$output6)
subjNames<-gsub('_SST.mat','',subjNames)
sst$subjectkey<-gsub('sub-NDARINV','NDAR_INV',subjNames)


```

```{r}
library(ggplot2)
library(reshape2)
# resting
dataR<-melt(rest[,2:5])
ggplot(dataR,aes(x=value,fill=variable))+geom_density(alpha=.25)+ggtitle('resting-state TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))
ggplot(dataR,aes(x=value,fill=variable))+geom_histogram(binwidth=50,alpha=.4,position='identity')+ggtitle('resting-state TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))

# nback
dataN<-melt(nback[,2:5])
ggplot(dataN,aes(x=value,fill=variable))+geom_density(alpha=.25)+ggtitle('nback TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))
ggplot(dataN,aes(x=value,fill=variable))+geom_histogram(binwidth=50,alpha=.4,position='identity')+ggtitle('nback-state TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))

# sst
datas<-melt(sst[,2:5])
ggplot(datas,aes(x=value,fill=variable))+geom_density(alpha=.25)+ggtitle('sst TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))
ggplot(datas,aes(x=value,fill=variable))+geom_histogram(binwidth=50,alpha=.4,position='identity')+ggtitle('sst-state TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))

# mid
datam<-melt(mid[,2:5])
ggplot(datam,aes(x=value,fill=variable))+geom_density(alpha=.25)+ggtitle('mid TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))
ggplot(datam,aes(x=value,fill=variable))+geom_histogram(binwidth=50,alpha=.4,position='identity')+ggtitle('mid-state TRs remaining')+scale_fill_manual(labels=c('Just .2mm FD and outliers','segments < 12 TRs discarded','< 18','< 24'),values = c("red", "blue","green","yellow"))
```

```{r}
# load in nda's gordon network rsfc
gordon=read.delim('~/Downloads/Package_1191523/abcd_betnet02.txt')
df<-merge(gordon,rest,by='subjectkey')
```

```{r}
df$rsfmri_c_ngd_dt_ngd_dla<-as.numeric(df$rsfmri_c_ngd_dt_ngd_dla)
df$rsfmri_c_ngd_dt_ngd_dt<-as.numeric(df$rsfmri_c_ngd_dt_ngd_dt)
df$rsfmri_c_ngd_smh_ngd_smh<-as.numeric(df$rsfmri_c_ngd_smh_ngd_smh)
df$rsfmri_c_ngd_smh_ngd_fo<-as.numeric(df$rsfmri_c_ngd_smh_ngd_fo)
```

```{r}
# DMN metrics and included TRs
cor.test(df$rsfmri_c_ngd_dt_ngd_dt,df$output2)
cor.test(df$rsfmri_c_ngd_dt_ngd_dt,df$output3)
cor.test(df$rsfmri_c_ngd_dt_ngd_dt,df$output4)
cor.test(df$rsfmri_c_ngd_dt_ngd_dt,df$output5)

ggplot(df,aes(df$rsfmri_c_ngd_dt_ngd_dt,df$output2))+geom_point()+geom_smooth(method='lm')+xlab('Within-DMN FC')+ylab('TRs passing thresh')


cor.test(df$rsfmri_c_ngd_dt_ngd_dla,df$output2)
cor.test(df$rsfmri_c_ngd_dt_ngd_dla,df$output3)
cor.test(df$rsfmri_c_ngd_dt_ngd_dla,df$output4)
cor.test(df$rsfmri_c_ngd_dt_ngd_dla,df$output5)

ggplot(df,aes(df$rsfmri_c_ngd_dt_ngd_dla,df$output2))+geom_point()+geom_smooth(method='lm')+xlab('DMN-DAN FC')+ylab('TRs passing thresh')
```


```{r}
# read in mental health (cbcl) items
cbcl<-read.delim('~/Downloads/Package_1191879/abcd_cbcls01.txt')
cbcl_bv=subset(cbcl,cbcl$eventname=='baseline_year_1_arm_1')
df<-merge(df,cbcl_bv,by='subjectkey')
cor.test(as.numeric(df$cbcl_scr_syn_internal_t),df$output3)
cor.test(as.numeric(df$cbcl_scr_syn_external_t),df$output3)

nihTB<-read.delim('~/Downloads/Package_1191879/abcd_tbss01.txt')
nihTB_bv=subset(nihTB,nihTB$eventname=='baseline_year_1_arm_1')
df<-merge(df,nihTB_bv,by='subjectkey')
cor.test(as.numeric(df$nihtbx_cryst_fc),df$output3)
cor.test(as.numeric(df$nihtbx_fluidcomp_fc),df$output3)
```

```{r}

```