---
title: "distancePlotting"
output: html_document
---

```{r}
#################################################################
# Calculate HierarchD, scatterplot Distances (FC vs. CFC, Yo vs. Old, Euc D vs. HierarchD)
#################################################################
#################################################################

```

```{r}
###### load in Hierarchy, Calculate Distance, save to RDS for local loadin

# vertices

vertPG_L<-read.csv('~/results/PWs/vertPG_left.csv')
vertPG_R<-read.csv('~/results/PWs/vertPG_right.csv')
# faces
facePG_L<-read.csv('~/results/PWs/facePG_left.csv')
facePG_R<-read.csv('~/results/PWs/facePG_right.csv')
# Initialize HierarchD matrices
HD_v_l<-matrix(nrow=dim(vertPG_L)[1],ncol=dim(vertPG_L)[1])
HD_v_r<-matrix(nrow=dim(vertPG_R)[1],ncol=dim(vertPG_R)[1])
HD_f_l<-matrix(nrow=dim(facePG_L)[1],ncol=dim(facePG_L)[1])
HD_f_r<-matrix(nrow=dim(facePG_R)[1],ncol=dim(facePG_R)[1])
##### Calculate HierarchD

# vertices

# L
for (i in 1:dim(vertPG_L)[1]){
  for (j in 1:dim(vertPG_L)[1]){
    # absolute valued distance
    HD_v_l[i,j]<-abs(vertPG_L[i,1]-vertPG_L[j,1])
  }
}

# saveout
saveRDS(HD_v_l,'~/data/HD_v_l.rds')

# R

for (i in 1:dim(vertPG_R)[1]){
  print('right')
  for (j in 1:dim(vertPG_R)[1]){
    # absolute valued distance
    HD_v_r[i,j]<-abs(vertPG_R[i,1]-vertPG_R[j,1])
  }
}

print('done with vertices')

# saveout
saveRDS(HD_v_r,'~/data/HD_v_r.rds')

# faces

# L
for (i in 1:dim(facePG_L)[1]){
  for (j in 1:dim(facePG_L)[1]){
    # absolute valued distance
    HD_f_l[i,j]<-abs(facePG_L[i,1]-facePG_L[j,1])
  }
}

# saveout
saveRDS(HD_f_l,'~/data/HD_f_l.rds')

# R 

for (i in 1:dim(facePG_R)[1]){
  print(i)
  for (j in 1:dim(facePG_R)[1]){
    # absolute valued distance
    HD_f_r[i,j]<-abs(facePG_R[i,1]-facePG_R[j,1])
  }
}

# saveout
saveRDS(HD_f_r,'~/data/HD_f_r.rds')

```

```{r}
# take upper triangle of euclidean distances, save for chance at mount loading
ED_f_l=read.csv('/cbica/projects/pinesParcels/results/PWs/face_EucD_left.csv')
saveRDS(ED_f_l[upper.tri(ED_f_l)],'/cbica/projects/pinesParcels/results/PWs/face_EucD_left_vec.rds')
ED_f_r=read.csv('/cbica/projects/pinesParcels/results/PWs/face_EucD_right.csv')
saveRDS(ED_f_r[upper.tri(ED_f_r)],'/cbica/projects/pinesParcels/results/PWs/face_EucD_right_vec.rds')
```

```{r}
# take upper triangle of fc, save for chance at mount loading
```

```{r}
library(vroom)
# take upper triangle of CFC, save for chance at mount loading
cfc_l=read.csv('/cbica/projects/pinesParcels/results/PWs/FC/gro_CFC_l.csv')
saveRDS(cfc_l[upper.tri(cfc_l)],'/cbica/projects/pinesParcels/results/PWs/FC/gro_CFC_l_vec.rds')
cfc_r=read.csv('/cbica/projects/pinesParcels/results/PWs/FC/gro_CFC_r.csv')
saveRDS(cfc_r[upper.tri(cfc_r)],'/cbica/projects/pinesParcels/results/PWs/FC/gro_CFC_r_vec.rds')
```

```{r}
# take upper triangle of hierarchical distance, save for chance at mount loading
HD_f_l=HD_f_l=readRDS('/cbica/projects/pinesParcels/data/HD_f_l.rds')
saveRDS(HD_f_l[upper.tri(HD_f_l)],'/cbica/projects/pinesParcels/data/HD_f_l.rds')
HD_f_r=HD_f_r=readRDS('/cbica/projects/pinesParcels/data/HD_f_r.rds')
saveRDS(HD_f_r[upper.tri(HD_f_r)],'/cbica/projects/pinesParcels/data/HD_f_r.rds')
```

```{r}
#### Load in distances, plot (FACES)
HD_f_l=readRDS('Y:/data/HD_f_l.rds')
HD_f_r=readRDS('Y:/data/HD_f_r.rds')

#### Load in Euclidean distances
ED_f_l=readRDS('Y:/results/PWs/face_EucD_left_vec.rds')
ED_f_r=readRDS('Y:/results/PWs/face_EucD_right_vec.rds')

### Load in CFC

cfc_l=readRDS('Y:/results/PWs/FC/gro_CFC_l_vec.rds')
cfc_r=readRDS('Y:/results/PWs/FC/gro_CFC_r_vec.rds')

```

```{r}
df<-data.frame(cfc_l,ED_f_l,HD_f_l)
colnames(df)<-c('cfc','ED','HD')

library(ggplot2)
ggplot(df, aes(y = cfc, x = ED)) +
  geom_hex(bins = 100)+scale_fill_gradient2(mid='gray90',high='black')+theme_classic()

```

```{r}
### read medial wall for vertices
mw_l_verts=as.logical(read.csv('~/data/mw_boolean_l.csv'))
mw_r_verts=as.logical(read.csv('~/data/mw_boolean_r.csv'))

# VERT FC
fc=read.csv('/cbica/projects/pinesParcels/results/PWs/FC/gro_FC.csv',header=F)
#mask out medial wall
fc_l=fc[1:10242,1:10242]
fc_l=fc_l[mw_l_verts,mw_l_verts]
# mask out lower triangle
saveRDS(fc_l[upper.tri(fc_l)],'/cbica/projects/pinesParcels/results/PWs/FC/gro_FC_l_vec.rds')

# right
#mask out medial wall
# add 10242 to mw r
fc_r=fc[10243:20484,10243:20484]
# mask out medial wall
fc_r=fc_r[mw_r_verts,mw_r_verts]
# mask out lower triangle
saveRDS(fc_r[upper.tri(fc_r)],'/cbica/projects/pinesParcels/results/PWs/FC/gro_FC_r_vec.rds')

# EUC D
ED_v_l=read.csv('/cbica/projects/pinesParcels/results/PWs/vert_EucD_left.csv')
#mask out medial wall
ED_v_l=ED_v_l[mw_l_verts,mw_l_verts]
# mask out lower triangle
saveRDS(ED_v_l[upper.tri(ED_v_l)],'/cbica/projects/pinesParcels/results/PWs/FC/vert_EucD_left_vec.rds')


# right
ED_v_r=read.csv('/cbica/projects/pinesParcels/results/PWs/vert_EucD_right.csv')
# mask out medial wall
ED_v_r=ED_v_r[mw_r_verts,mw_r_verts]
# mask out lower triangle
saveRDS(ED_v_r[upper.tri(ED_v_r)],'/cbica/projects/pinesParcels/results/PWs/FC/vert_EucD_right_vec.rds')

# HIER D
HD_v_l=readRDS('/cbica/projects/pinesParcels/data/HD_v_l.rds')
HD_v_r=readRDS('/cbica/projects/pinesParcels/data/HD_v_r.rds')

# left
HD_v_l=HD_v_l[mw_l_verts,mw_l_verts]
saveRDS(HD_v_l[upper.tri(HD_v_l)],'/cbica/projects/pinesParcels/data/HD_v_l.rds')

# right
HD_v_r=HD_v_r[mw_r_verts,mw_r_verts]
saveRDS(HD_v_r[upper.tri(HD_v_r)],'/cbica/projects/pinesParcels/data/HD_v_r.rds')

```

```{r}
### Load in Vertex data
HD_v_l=readRDS('Y:/data/HD_v_l.rds')
HD_v_r=readRDS('Y:/data/HD_v_r.rds')
ED_v_l=readRDS('Y:/results/PWs/FC/vert_EucD_left_vec.rds')
ED_v_r=readRDS('Y:/results/PWs/FC/vert_EucD_right_vec.rds')
fc_l=readRDS('Y:/results/PWs/FC/gro_FC_l_vec.rds')
fc_r=readRDS('Y:/results/PWs/FC/gro_FC_r_vec.rds')
```

```{r}
df<-data.frame(fc_l,ED_v_l,HD_v_l)
colnames(df)<-c('fc','ED','HD')

library(ggplot2)
library(ggExtra)
ggplot(df, aes(y = fc, x = ED)) +
  geom_hex(bins = 100)+scale_fill_gradient2(mid='gray90',high='black',limits=c(900000))+theme_classic()
# plot just for marginal
Marginal<-ggplot(df, aes(y = fc, x = HD)) +geom_point(alpha=0,size=0)+theme_classic()
ggMarginal(Marginal,type='histogram')
```


```{r}
# will need sep. runs for young and old
##### load in FC

# young
yfc=vroom('/cbica/projects/pinesParcels/results/PWs/FC/gro_FC_young.csv',col_names=FALSE)
ycfc_l=vroom('Y:/results/PWs/FC/gro_CFC_young_l.csv',col_names=FALSE)
ycfc_r=vroom('Y:/results/PWs/FC/gro_CFC_young_r.csv',col_names=FALSE)
```

```{r}
# old
ofc=read.csv('/cbica/projects/pinesParcels/results/PWs/FC/gro_FC_old.csv')

##### load in CFC

# old
ocfc_l=vroom('Y:/results/PWs/FC/gro_CFC_old_l.csv',col_names=FALSE)
ocfc_r=vroom('Y:/results/PWs/FC/gro_CFC_old_r.csv',col_names=FALSE)

ocfc_l=read.csv('/cbica/projects/pinesParcels/results/PWs/FC/gro_CFC_old_l.csv',header=F)
ocfc_r=read.csv('/cbica/projects/pinesParcels/results/PWs/FC/gro_CFC_old_r.csv',header=F)




##### combine all into dataframe
df<-data.frame(ED_f_l[upper.tri(ED_f_l)],ocfc_l[upper.tri(ocfc_l)],HD_f_l)
colnames(df)<-c('Distance','CFC_o','HierarchD')
```

```{r}
library(ggplot2)
ggplot(df, aes(y = CFC_o, x = Distance)) +
  geom_hex(bins = 200)
ggplot(df, aes(y = CFC_o, x = HierarchD)) +
  geom_hex(bins = 200)
ggplot(df, aes(y = Distance, x = HierarchD)) +
  geom_hex(bins = 200)
```

```{r}
# for running on cluster
.libPaths('~/Rlibs')
library(ggplot2)
library(hexbin)
fc_l=readRDS('/cbica/projects/pinesParcels/results/PWs/FC/gro_FC_l_vec.rds')
HD_v_l=readRDS('/cbica/projects/pinesParcels/data/HD_v_l.rds')
df=data.frame(fc_l,HD_v_l)
colnames(df)<-c('FC','HierarchD')
theplot<-ggplot(df, aes(y = FC, x = HierarchD)) +
  geom_hex(bins = 80)+geom_smooth(method='gam',formula = y~s(x,k=4))+theme_classic()
ggsave('~/test.png',theplot)
```

```{r}
# load participant-specific associations
df1<-readRDS('Y:/data/mergedDF_withDistanceCorrs_1.rds')
df2<-readRDS('Y:/data/mergedDF_withDistanceCorrs_2.rds')
df3<-readRDS('Y:/data/mergedDF_withDistanceCorrs_3.rds')
df4<-readRDS('Y:/data/mergedDF_withDistanceCorrs_4.rds')
df5<-readRDS('Y:/data/mergedDF_withDistanceCorrs_5.rds')
#df6<-readRDS('Y:/data/mergedDF_withDistanceCorrs_6.rds')
df7<-readRDS('Y:/data/mergedDF_withDistanceCorrs_7.rds')
df8<-readRDS('Y:/data/mergedDF_withDistanceCorrs_8.rds')

# merge it back together from sep. processing chunks
df<-rbind(df1,df2,df3,df4,df5,df6,df7,df8)
```