---
title: "Group_level"
output: html_document
---

```{r}
library(shapes)
library(ggplot2)
library(mgcv)
```

```{r}
# load in subj list
subjList=read.delim('Y:/PWs/hcpd_subj_list.txt')

# load in ages
demo=read.csv('Y:/PWs/hcpd_demographics.csv')
# convert to used naming convention
demo$SubjID<-gsub('HCD','sub-',demo$src_subject_id)

# load in FD
FD_TRs=read.csv('Y:/PWs/Subj_FD_RemTRs.csv')
colnames(FD_TRs)[1]<-'SubjID'
colnames(FD_TRs)[2]<-'FD'
colnames(FD_TRs)[3]<-'RemainingTRs'

# merge by subjID
mergeddf<-merge(demo,FD_TRs,by='SubjID')

# initialize D
Ds=rep(0,dim(subjList)[1])
Ps=rep(0,dim(subjList)[1])
remTRs=rep(0,dim(subjList)[1])

# subjvec to run in parallel for even more confidence in merging
Subjvec=rep(0,dim(subjList)[1])

# initialize shape matrix
shapeMat=array(dim=c(24,2,dim(subjList)[1]))
shapeMatAbs=array(dim=c(24,2,dim(subjList)[1]))

# load in D and shapes iteratively
for (s in 1:dim(subjList)[1]){
    subj=subjList[s,1]
    ResFp=paste0('Y:/results/PWs/Proced/',subj,'/')
    # if output exists
    if (file.exists(paste0(ResFp,subj,'_gShapeMatrix.rds'))) {
      # load in shapemat
      shapemat=readRDS(paste0(ResFp,subj,'_gShapeMatrix.rds'))
      # scale it
      divisorPt2=24/(max(shapemat[,2])-min(shapemat[,2]))
      shapeMat[,1,s]=shapemat[,1]
      shapeMat[,2,s]=shapemat[,2]*divisorPt2
      # load in shapemat abs
      #shapematAbs=readRDS(paste0(ResFp,subj,'_AbsShapeMatrix.rds'))
      # scale it
      #divisorPt1a=max(shapematAbs[,2])
      #divisorPt2a=20/divisorPt1a
      #shapeMatAbs[,1,s]=shapematAbs[,1]
      #shapeMatAbs[,2,s]=shapematAbs[,2]*divisorPt2a
      # load in dip test
      dipstat=readRDS(paste0(ResFp,subj,'_gDipTest.rds'))
      Ds[s]=dipstat$statistic
      Ps[s]=dipstat$p.value
      # and to record same order of subj loading and prevent funny biz
      Subjvec[s]=subj
      print(s)
      # and remaining TRs
      remTRs[s]=mergeddf$RemainingTRs[mergeddf$SubjID==subj]
    }
}

# merge populated vecs
popDf=data.frame(Subjvec,Ds,Ps,remTRs)
colnames(popDf)[1]<-'SubjID'

# remaining TRs thresh
inclusionVec<-popDf$remTRs>600
includedSubjsvec<-popDf$SubjID[inclusionVec]
popDfThresh=popDf[popDf$remTRs>600,]
ThreshShapeMat<-shapeMat[,,inclusionVec]

masterdf=merge(mergeddf,popDfThresh,by='SubjID')

```
```{r}
# make list of old subjs vs younger
low_tertile_age=quantile(masterdf$interview_age,.33)
high_tertile_age=quantile(masterdf$interview_age,.66)

# youngins
youngins=masterdf$SubjID[masterdf$interview_age<low_tertile_age]
write.table(youngins,'Y:/PWs/young_subs.csv')
#geezers
geezers=masterdf$SubjID[masterdf$interview_age>high_tertile_age]
write.table(geezers,'Y:/PWs/old_subs.csv')
```

```{r}
# read in discretized cross subj histograms (linear)
o_disthist<-t(read.csv('Y:/results/PWs/old_subs_AngDistHist.csv'))
y_disthist<-t(read.csv('Y:/results/PWs/young_subs_AngDistHist.csv'))

# normalize to total numbers
o_disthist<-o_disthist/sum(o_disthist)
y_disthist<-y_disthist/sum(y_disthist)

difHist=o_disthist-y_disthist

barplot(t(o_disthist),ylim=c(0,0.07),main = 'Old r.s. OpFl Directionality',xlab='0-180')

barplot(t(y_disthist),ylim=c(0,0.07),main = 'Young OpFl Directionality',xlab='0-180')

barplot(t(difHist),main='Difference in OpFl Directionality',xlab='0-180')

#### young fancy
plotdataf<-data.frame(seq(1,18),y_disthist)
# correct to be degrees rather than histogram bin index
plotdataf$seq.1..18.<-plotdataf$seq.1..18.*10

p<-ggplot(plotdataf,aes(x=seq.1..18.,y=y_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: 8-14")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')


#### old fancy
plotdataf<-data.frame(seq(1,18),o_disthist)
# correct to be degrees rather than histogram bin index
plotdataf$seq.1..18.<-plotdataf$seq.1..18.*10

p<-ggplot(plotdataf,aes(x=seq.1..18.,y=o_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: 17-21")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')

#difference fancy

plotdataf<-data.frame(seq(1,18),o_disthist-y_disthist)
# correct to be degrees rather than histogram bin index
plotdataf$seq.1..18.<-plotdataf$seq.1..18.*10

p<-ggplot(plotdataf,aes(x=seq.1..18.,y=o_disthist...y_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: Dif")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')


# load in permuted old young dif
PermDif=read.csv('Y:/results/PWs/Old_v_young_AngDistDif_permuted.csv')
permDf<-data.frame(PermDif)

# make vectors of mean values of permuted at each bin
meanVec=colMeans(permDf[1:1000,])
# make vectors of 95 and 5th percentile of permuted at each bin
topPercVec=unlist(lapply(permDf[1:1000,1:18],quantile,prob=.95,names=F))
botPercVec=unlist(lapply(permDf[1:1000,1:18],quantile,prob=.05,names=F))

plotdataf$meanVec=meanVec
plotdataf$topPercVec=topPercVec
plotdataf$botPercVec=botPercVec

plotdf<-data.frame(meanVec,topPercVec,botPercVec,seq(1:18),t(PermDif[1001,]))


# keller kode
ggplot(plotdf)+geom_ribbon(aes(x=seq.1.18.*10,ymin=botPercVec*100,ymax=topPercVec*100),fill='gray80')+geom_step(aes(x=seq.1.18.*10,y=X1001*100),color='blue',size=2)+theme_classic(base_size = 30)+xlab("Angular Distance (degrees)")+ylab('Percentage Difference')

p<-ggplot(plotdataf,aes(x=seq.1..18.,y=o_disthist...y_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: Dif")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')+geom_ribbon(aes(x=seq.1..18.,ymin=botPercVec,ymax=topPercVec),fill='gray80',alpha=.5)

### aaaaand permuted task vs rest dif

```

```{r}
library(scales)
# read in discretized cross subj histograms (linear, modes)
o_disthist<-t(read.csv('Y:/results/PWs/old_subs_AngDistHist_modedOverTRs.csv'))
y_disthist<-t(read.csv('Y:/results/PWs/young_subs_AngDistHist_modedOverTRs.csv'))

# normalize to total numbers
o_disthist<-o_disthist/sum(o_disthist)
y_disthist<-y_disthist/sum(y_disthist)

difHist=o_disthist-y_disthist

barplot(t(o_disthist),ylim=c(0,0.2),main = 'Old r.s. OpFl Directionality',xlab='0-180')

barplot(t(y_disthist),ylim=c(0,0.2),main = 'Young OpFl Directionality',xlab='0-180')

barplot(t(difHist),main='Difference in OpFl Directionality',xlab='0-180')

# correct to be degrees rather than histogram bin index
plotdataf<-data.frame(seq(10,170,10),y_disthist)
# correct to be degrees rather than histogram bin index
colnames(plotdataf)<-c('index','y_disthist')

p<-ggplot(plotdataf,aes(x=index,y=y_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(5,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"),guide=guide_colorbar(ticks = F))+ggtitle("Angular Distance: 8-14 Modes")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')

# correct to be degrees rather than histogram bin index
plotdataf<-data.frame(seq(10,170,10),o_disthist)
# correct to be degrees rather than histogram bin index
colnames(plotdataf)<-c('index','o_disthist')

p<-ggplot(plotdataf,aes(x=index,y=o_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(5,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"),guide=guide_colorbar(ticks = F))+ggtitle("Angular Distance: 17-21 Modes")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')

# dif
# correct to be degrees rather than histogram bin index
plotdataf<-data.frame(seq(10,170,10),o_disthist-y_disthist)
# correct to be degrees rather than histogram bin index
colnames(plotdataf)<-c('index','dif_disthist')

p<-ggplot(plotdataf,aes(x=index,y=dif_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(5,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"),guide=guide_colorbar(ticks = F))+ggtitle("Angular Distance: Modal Difference")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')+scale_y_continuous(labels = percent_format(accuracy = 1))
```


```{r}
### make subject lists for RS (388), RS w/ good _C, and good _C

###### 388
rs_subs<-masterdf$SubjID
#print
write.table(rs_subs,'Y:/PWs/rs_subs.csv')

#### RS_C matched: rope in a bunch of goblyguk just for equivalence with facewise_t
# load in FD
FD_TRs=read.csv('Y:/PWs/Subj_FD_RemTRs.csv')
colnames(FD_TRs)[1]<-'SubjID'
colnames(FD_TRs)[2]<-'FD'
colnames(FD_TRs)[3]<-'RemainingTRs'
# FD for carit runs
FD_TRs_c=read.csv('Y:/PWs/Subj_FD_RemTRs_c.csv')
colnames(FD_TRs_c)[1]<-'SubjID'
colnames(FD_TRs_c)[2]<-'FDc'
colnames(FD_TRs_c)[3]<-'RemainingTRsc'
# merge by subjID
mergeddf<-merge(demo,FD_TRs,by='SubjID')
mergeddf<-merge(mergeddf,FD_TRs_c,by='SubjID')
# exclude subjects with less than 600 TRs remaining (in rest)
inclusionVec<-mergeddf$RemainingTRs>600
# include NAs in the exclusion
inclusionVec[is.na(inclusionVec)==TRUE]=FALSE
# subset the master df accordingly
mergeddf<-mergeddf[inclusionVec,]
# get count of remaining subjects
remainingSubjs=dim(mergeddf)[1]
print(remainingSubjs)
# exclude subjects with less than 300 TRs remaining (in carit)
inclusionVec<-mergeddf$RemainingTRsc>300
# include NAs in the exclusion
inclusionVec[is.na(inclusionVec)==TRUE]=FALSE
# subset the master df accordingly
df<-mergeddf[inclusionVec,]
# get count of remaining subjects
remainingSubjs=dim(df)[1]
print(remainingSubjs)
# extract subjs
rs_cmatch_subjs<-df$SubjID
# print
write.table(rs_cmatch_subjs,'Y:/PWs/rs_cmatch_subs.csv')

# _C: will need FP alteration in .m, but is from same subjects

```

```{r}
library(scales)
# quick checkup on how BuProp from hists (and rs_subs.csv) maps onto bimodality
BuProp=t(read.csv('Y:/results/PWs/rs_subsBuProp.csv'))
Subjs=read.delim('Y:/PWs/rs_subs.csv',sep=' ')
BuPropdf<-data.frame(BuProp,Subjs)
colnames(BuPropdf)<-c('BuProp','SubjID')
BuMerge<-merge(BuPropdf,masterdf,by='SubjID')

#plotting
BuDs<-ggplot(BuMerge,aes(x=Ds,y=1-BuProp))+geom_point(size=3,alpha=.5)+theme_classic(base_size=28)+geom_smooth(method='lm',color='black')
BuDs+xlab('Dip Statistics')+ylab('Top-Down')+scale_y_continuous(labels = percent_format(accuracy = 1))+scale_x_continuous(breaks=c(.002,.006,.01))
```

```{r}
# read in discritized cross subj histograms (linear)
disthist<-t(read.csv('Y:/results/PWs/rs_subs_AngDistHist.csv'))
disthistModes<-t(read.csv('Y:/results/PWs/rs_subs_AngDistHist_modedOverTRs.csv'))
rs_disthist<-t(read.csv('Y:/results/PWs/RS_cmatch_subs_AngDistHist.csv'))
c_disthist<-t(read.csv('Y:/results/PWs/c_cmatch_subs_AngDistHist.csv'))
rs_disthistModes<-t(read.csv('Y:/results/PWs/RS_cmatch_subs_AngDistHist_modedOverTRs.csv'))
c_disthistModes<-t(read.csv('Y:/results/PWs/c_cmatch_subs_AngDistHist_modedOverTRs.csv'))

# normalize to total numbers
rs_disthist<-rs_disthist/sum(rs_disthist)
c_disthist<-c_disthist/sum(c_disthist)
disthist<-disthist/sum(disthist)
disthistModes<-disthistModes/sum(disthistModes)
rs_disthistModes<-rs_disthistModes/sum(rs_disthistModes)
c_disthistModes<-c_disthistModes/sum(c_disthistModes)

difHist=c_disthist-rs_disthist
difHistModes=c_disthistModes-rs_disthistModes

barplot(t(disthist),ylim=c(0,0.07),main = 'OpFl Directionality',xlab='0-180')



barplot(t(rs_disthist),ylim=c(0,0.07),main = 'Resting State OpFl Directionality',xlab='0-180')

barplot(t(c_disthist),ylim=c(0,0.07),main = 'Carit OpFl Directionality',xlab='0-180')

barplot(t(difHist),main='Difference in OpFl Directionality',xlab='0-180')

barplot(t(disthistModes),ylim=c(0,.2),main='Facial Modes OpFl Directionality',xlab='0-180')

barplot(t(rs_disthistModes),ylim=c(0,.2),main='Facial Modes OpFl Directionality: rs',xlab='0-180')

barplot(t(c_disthistModes),ylim=c(0,.2),main='Facial Modes OpFl Directionality: carit',xlab='0-180')


barplot(t(difHistModes),main='Facial Modes Difference in OpFl Directionality',xlab='0-180')


###########
plotdataf<-data.frame(seq(1,18),disthist)
# correct to be degrees rather than histogram bin index
plotdataf$seq.1..18.<-plotdataf$seq.1..18.*10

p<-ggplot(plotdataf,aes(x=seq.1..18.,y=disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.1, unit='cm'))+ylab('count')

# correct to be degrees rather than histogram bin index
plotdataf<-data.frame(seq(10,170,10),disthistModes)
# correct to be degrees rather than histogram bin index
colnames(plotdataf)<-c('index','disthistModes')

p<-ggplot(plotdataf,aes(x=index,y=disthistModes))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(5,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"),guide=guide_colorbar(ticks = F))+ggtitle("Angular Distance: Facial Modes")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.1, unit='cm'))+ylab('count')

#### resting state cmatched
plotdataf<-data.frame(seq(1,18),rs_disthist)
# correct to be degrees rather than histogram bin index
plotdataf$seq.1..18.<-plotdataf$seq.1..18.*10

p<-ggplot(plotdataf,aes(x=seq.1..18.,y=rs_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: RS")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')

# correct to be degrees rather than histogram bin index
plotdataf<-data.frame(seq(10,170,10),rs_disthistModes)
# correct to be degrees rather than histogram bin index
colnames(plotdataf)<-c('index','rs_disthistModes')

p<-ggplot(plotdataf,aes(x=index,y=rs_disthistModes))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(5,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"),guide=guide_colorbar(ticks = F))+ggtitle("Angular Distance: RS Facial Modes")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')

#### carit
plotdataf<-data.frame(seq(1,18),c_disthist)
# correct to be degrees rather than histogram bin index
plotdataf$seq.1..18.<-plotdataf$seq.1..18.*10

p<-ggplot(plotdataf,aes(x=seq.1..18.,y=c_disthist))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: Carit")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')

# correct to be degrees rather than histogram bin index
plotdataf<-data.frame(seq(10,170,10),c_disthistModes)
# correct to be degrees rather than histogram bin index
colnames(plotdataf)<-c('index','c_disthistModes')

p<-ggplot(plotdataf,aes(x=index,y=c_disthistModes))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(5,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"),guide=guide_colorbar(ticks = F))+ggtitle("Angular Distance: Carit Facial Modes")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')


```

```{r}
# difference hists
plotdataf<-data.frame(seq(1,18),c_disthist-rs_disthist)
# correct to be degrees rather than histogram bin index
plotdataf$seq.1..18.<-plotdataf$seq.1..18.*10
colnames(plotdataf)<-c('index','difdisthist')

p<-ggplot(plotdataf,aes(x=index,y=difdisthist))

p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("difdisthist",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: Carit")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')


plotdataf<-data.frame(seq(10,170,10),c_disthistModes-rs_disthistModes)
# correct to be degrees rather than histogram bin index
colnames(plotdataf)<-c('index','difdisthistmodes')

p<-ggplot(plotdataf,aes(x=index,y=difdisthistmodes))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(5,180)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"),guide=guide_colorbar(ticks = F))+ggtitle("Angular Distance: Modal Difference")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')+scale_y_continuous(labels = percent_format(accuracy = 1))
```

```{r}
### aaaaand permuted task vs rest dif
PermDif=read.csv('Y:/results/PWs/Task_v_rest_AngDistDif_permuted.csv')
permDf<-data.frame(PermDif)

# make vectors of mean values of permuted at each bin
meanVec=colMeans(permDf[1:1000,])
# make vectors of 95 and 5th percentile of permuted at each bin
topPercVec=unlist(lapply(permDf[1:1000,1:18],quantile,prob=.95,names=F))
botPercVec=unlist(lapply(permDf[1:1000,1:18],quantile,prob=.05,names=F))

plotdf<-data.frame((c_disthist-rs_disthist),meanVec,topPercVec,botPercVec,seq(1:18),t(PermDif[1001,]))


# keller kode
ggplot(plotdf)+geom_ribbon(aes(x=seq.1.18.*10,ymin=botPercVec*100,ymax=topPercVec*100),fill='gray80')+geom_step(aes(x=seq.1.18.*10,y=X1001*100),color='blue',size=2)+theme_classic(base_size = 30)+xlab("Angular Distance (degrees)")+ylab('Percentage Difference')

#
p<-ggplot(plotdf,aes(x=seq.1.18.*10,y=X1001))
p+geom_ribbon(aes(x=seq.1.18.*10,ymin=botPercVec,ymax=topPercVec),fill='gray80',alpha=1)+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10,alpha=.8)+xlab("Distance (Degrees)")+theme_classic(base_size = 23)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle("Angular Distance over all TRs: Dif")+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.08,.41),plot.margin=margin(b=.1,t=.1,l=.1,r=2.3, unit='cm'))+ylab('count')
```

```{r}
library(visreg)
# convert to prop TD
BuMerge$TDProp=1-BuMerge$BuProp

# dev analyses
visreg(gam(TDProp~s(interview_age,k=4)+FD+sex,data=BuMerge))

# get residuals of model for plotting
TDProp_lm<-lm(TDProp~FD+sex,data=BuMerge)
BuMerge$TDProp_resid<-TDProp_lm$residuals+mean(BuMerge$TDProp)

ggplot(BuMerge,aes(x=(interview_age)/12,y=TDProp_resid)) + geom_smooth(method = 'gam', formula = y~s(x,k=4), colour=('#4b5e72'), fill = "#7b98b7", alpha = .8) + geom_point(size=3,alpha=.6) + xlab("Age") +ylab("Top-Down Propagations") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank()) + theme(axis.line.x = element_line(colour = 'black', size = 2), axis.line.y = element_line(colour = 'black', size = 2), axis.ticks.length = unit(.25, "cm"), axis.text = element_text(face="bold",size=30), axis.title = element_text(size=30, face="bold"), axis.title.y = element_text(margin = margin(t = 0, r = 47, b = 0, l = 0))) +scale_y_continuous(labels = percent_format(accuracy = 1))


# aaaand combat chunk on it
library(devtools)
#install_github("jfortin1/neuroCombatData")
#install_github("jfortin1/neuroCombat_Rpackage")

library(neuroCombat)

# get site info
BuMerge$d_site<-droplevels(as.factor(BuMerge$site))
batch <- BuMerge$d_site
BuMerge.toharmonize <- BuMerge[,c("TDProp","FD")]
mod <- model.matrix(~BuMerge$interview_age+BuMerge$sex)
dat <- t(BuMerge.toharmonize)
hcpd.data.combat <- neuroCombat(dat=dat,mod=mod,batch=batch,eb=FALSE)
dat.harmonized<-data.frame(t(hcpd.data.combat$dat.combat))

BuMerge$harmTDProp<-dat.harmonized$TDProp
BuMerge$harmFD<-dat.harmonized$FD

visreg(gam(harmTDProp~s(interview_age,k=4)+harmFD+sex,data=BuMerge))
```

```{r}
write.table(masterdf$SubjID,'~/G600_TRs.txt',quote = F,col.names = F,row.names = F)
```

```{r}
# mean direction by pg bins
meanDirb1=t(read.csv('Y:/PWs/scripts/MeanDir_Bin1.csv'))
plotdf<-data.frame(meanDirb1)
ggplot(plotdf,aes(meanDirb1,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb2=t(read.csv('Y:/PWs/scripts/MeanDir_Bin2.csv'))

plotdf<-data.frame(meanDirb2)
ggplot(plotdf,aes(meanDirb2,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb3=t(read.csv('Y:/PWs/scripts/MeanDir_Bin3.csv'))

plotdf<-data.frame(meanDirb3)
ggplot(plotdf,aes(meanDirb3,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb4=t(read.csv('Y:/PWs/scripts/MeanDir_Bin4.csv'))

plotdf<-data.frame(meanDirb4)
ggplot(plotdf,aes(meanDirb4,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb5=t(read.csv('Y:/PWs/scripts/MeanDir_Bin5.csv'))

plotdf<-data.frame(meanDirb5)
ggplot(plotdf,aes(meanDirb5,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb6=t(read.csv('Y:/PWs/scripts/MeanDir_Bin6.csv'))

plotdf<-data.frame(meanDirb6)
ggplot(plotdf,aes(meanDirb6,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb7=t(read.csv('Y:/PWs/scripts/MeanDir_Bin7.csv'))

plotdf<-data.frame(meanDirb7)
ggplot(plotdf,aes(meanDirb7,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb8=t(read.csv('Y:/PWs/scripts/MeanDir_Bin8.csv'))

plotdf<-data.frame(meanDirb8)
ggplot(plotdf,aes(meanDirb8,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb9=t(read.csv('Y:/PWs/scripts/MeanDir_Bin9.csv'))

plotdf<-data.frame(meanDirb9)
ggplot(plotdf,aes(meanDirb9,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))


meanDirb10=t(read.csv('Y:/PWs/scripts/MeanDir_Bin10.csv'))

plotdf<-data.frame(meanDirb10)
ggplot(plotdf,aes(meanDirb10,fill=..x..))+geom_histogram()+coord_polar(start=3.1416)+theme_classic()+scale_fill_gradientn("meanDirb1",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"))
```


```{r}
# read in discretized cross subj histograms (circular)
disthist<-t(read.csv('Y:/PWs/rs_subs_AngDistHist360.csv',header=F))
disthistModes<-t(read.csv('Y:/PWs/rs_subs_AngDistHist360_modedOverTRs.csv',header=F))

plotdf<-data.frame(disthist)
plotdf$index<-seq(1:36)

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = round(as.numeric(disthist)))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)


# plot
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-100000000,150000000))

##### same for modes
plotdf<-data.frame(disthistModes[1,])
plotdf$index<-seq(1:36)

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = round(as.numeric(disthistModes.1...)))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)


# plot
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-10000,223000))


```

```{r}
# read in discretized cross subj histograms (circular) - Young/Old
disthist<-t(read.csv('Y:/PWs/young_subs_AngDistHist360.csv',header=F))
disthistModes<-t(read.csv('Y:/PWs/young_subs_AngDistHist360_modedOverTRs.csv',header=F))

plotdf<-data.frame(disthist)
plotdf$index<-seq(1:36)

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = round(as.numeric(disthist)))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)


# plot
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-40000000,45000000))

##### same for modes
plotdf<-data.frame(disthistModes[1,])
plotdf$index<-seq(1:36)

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = round(as.numeric(disthistModes.1...)))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)


# plot
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-40000,74000))

#####################
#### and old folk
#####################

disthistO<-t(read.csv('Y:/PWs/old_subs_AngDistHist360.csv',header=F))
disthistModesO<-t(read.csv('Y:/PWs/old_subs_AngDistHist360_modedOverTRs.csv',header=F))
plotdf<-data.frame(disthistO)
plotdf$index<-seq(1:36)

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = round(as.numeric(disthistO)))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)


# plot
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-49000000,57000000))

##### same for modes
plotdf<-data.frame(disthistModesO[1,])
plotdf$index<-seq(1:36)

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = round(as.numeric(disthistModesO.1...)))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-40000,78000))


# convert to proporitons for meaningful difference calculation
disthistprop=disthist/sum(disthist)
disthistpropO=disthistO/sum(disthist0)
# same for modes
disthistpropM=disthistModes/sum(disthistModes)
disthistpropMO=disthistModesO/sum(disthistModes0)

# difference
plotdf$dif<-disthistpropO-disthistprop
plotdf$modedif<-disthistpropMO[1,]-disthistpropM[1,]

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = as.numeric(dif))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)


# plot
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-.0008,.0008))


# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = as.numeric(modedif))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)


# plot
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-.0002,.0002))

```

```{r}
plotdf<-data.frame(dif)
plotdf$index<-seq(1:36)

# Make the plot
p <- ggplot(plotdf, aes(x = as.factor(index), # x-axis factor label
					
					# y-axis numerical parameter
					y = round(as.numeric(disthistModesO.1...)))) +	

# the bar height will represent
# the actual value of the data
geom_bar(stat = "identity",color='black',
		aes(fill=index)) + # define bar color
# define the polar coordinate
coord_polar(start = 3.1416)
p+theme_minimal(base_size=24)+scale_fill_gradientn("index",colors=c("red","orange","yellow","green","cyan","blue","cyan","green","yellow","orange","red"),breaks=c(1,18,36),labels=c(expression(paste('-',pi)),0,expression(paste('',pi))))+theme(panel.grid.major=element_line(colour="black"),panel.grid.minor=element_line(colour="black"),legend.position = 'bottom',legend.key.width = unit(2,'cm'),legend.title = element_blank(),axis.text = element_blank(),axis.title.y=element_blank())+xlab('Distance (Radians)')+ylim(c(-40000,78000))

```

```{r}
# pgg magnitude distributions
PGGmagL_s=read.csv('Y:/data/vsumL.csv')
PGGmagR_s=read.csv('Y:/data/vsumR.csv')
PGGmagL_h=read.csv('Y:/data/vHL.csv')
PGGmagR_h=read.csv('Y:/data/vHR.csv')

vecSumCombined=c(PGGmagL_s$vsumL,PGGmagR_s$vsumR)
vecHypCombined=c(PGGmagL_h$vHL,PGGmagR_h$vHR)

# bottom 1%
b1p=quantile(vecHypCombined,.1)
b1=vecHypCombined<b1p

# sep. back out for plotting
b1l=b1[1:4851]
b1r=b1[4852:length(b1)]

# writeout
write.csv(as.numeric(b1l),'Y:/dropbox/b1maskL.csv')
write.csv(as.numeric(b1r),'Y:/dropbox/b1maskR.csv')
```
```
