---
title: "NullPlotting"
output: html_document
---

```{r}
library(ggplot2)
library(mgcv)

# for each subj, get observed vs. null spatial distribution/value
# load in subj list
subjList=read.delim('Y:/PWs/hcpd_subj_list.txt')

# load in ages
demo=read.csv('Y:/PWs/hcpd_demographics.csv')
# convert to used naming convention
demo$SubjID<-gsub('HCD','sub-',demo$src_subject_id)

# load in FD
FD_TRs=read.csv('Y:/PWs/Subj_FD_RemTRs.csv')
colnames(FD_TRs)[1]<-'SubjID'
colnames(FD_TRs)[2]<-'FD'
colnames(FD_TRs)[3]<-'RemainingTRs'

# merge by subjID
mergeddf<-merge(demo,FD_TRs,by='SubjID')

# initialize Dip SD
RealDips=rep(0,dim(subjList)[1])
DipSDs=rep(0,dim(subjList)[1])
CDipSDs=rep(0,dim(subjList)[1])

# keep track of remaining TRs
remTRs=rep(0,dim(subjList)[1])

# subjvec to run in parallel for even more confidence in merging
Subjvec=rep(0,dim(subjList)[1])

# for plopping all null dips into one vector
NullDips=matrix(ncol=1000,nrow=dim(subjList)[1])
CNullDips=matrix(ncol=1000,nrow=dim(subjList)[1])

# load in D and shapes iteratively
for (s in 1:dim(subjList)[1]){
    subj=subjList[s,1]
    ResFp=paste0('Y:/results/PWs/Proced/',subj,'/')
    # if output exists
    if (file.exists(paste0(ResFp,subj,'_ShufDips4.csv'))) {
      SpunDips<-read.csv(paste0('Y:/results/PWs/Proced/',subj,'/',subj,'_ShufDips4.csv'),header=F)
      ObsDip<-as.numeric(SpunDips[2,101])
      RealDips[s]<-ObsDip
      SpunDips<-as.numeric(SpunDips[2,1:100])
      SpunSD=sd(SpunDips)
      SpunMean=mean(SpunDips)
      #print(ObsDip)
      # insert into df
      NullDips[s,]=SpunDips
      #print(SpunMean)
      DipSDs[s]=(ObsDip-SpunMean)/SpunSD
      remTRs[s]=mergeddf$RemainingTRs[mergeddf$SubjID==subj]
      # and to record same order of subj loading and prevent funny biz
      Subjvec[s]=subj

    }
}

# merge populated vecs
popDf=data.frame(Subjvec,DipSDs,CDipSDs,RealDips,remTRs)
colnames(popDf)[1]<-'SubjID'

# remaining TRs thresh
inclusionVec<-popDf$remTRs>600
includedSubjsvec<-popDf$SubjID[inclusionVec]
popDfThresh=popDf[popDf$remTRs>600,]

masterdf=merge(mergeddf,popDfThresh,by='SubjID')
```

```{r}
# for spatial
ggplot(popDfThresh,aes(x=DipSDs))+geom_histogram(fill='#BC3754')+theme_classic(base_size=23)+xlim(0,25)+xlab('Standard Deviations from Nulls')+theme(axis.text = element_text(size=23))+ylab('Participants')+geom_vline(xintercept = median(popDfThresh$DipSDs),linetype='dashed',size=2)

# for temporal
ggplot(popDfThresh,aes(x=DipSDs))+geom_histogram(fill='#BC3754')+theme_classic(base_size=23)+xlim(0,100)+xlab('Standard Deviations from Nulls')+theme(axis.text = element_text(size=23))+ylab('Participants')+geom_vline(xintercept = median(popDfThresh$DipSDs),linetype='dashed',size=2)


# saved at 500x250
```

```{r}
ggplot(popDfThresh,aes(x=CDipSDs))+geom_histogram(fill='#BC3754')+theme_classic(base_size=23)+xlab('Standard Deviations of Observed from Nulls')
```

```{r}
# get group-wide null distribution for those that passed QC
NullDipsThresh=NullDips[popDf$remTRs>600,]

# get all spun dips
SpunDips<-as.numeric(NullDipsThresh)
# get mean and SD to compare across subjs
meanSpunDips<-mean(SpunDips)
SDSpunsDips<-sd(SpunDips)

# get 99th percentile of nulls
nineninePercentile=quantile(SpunDips,probs=c(0.01,0.99))[2]

# convert Obs Dips in terms of SD to real terms of typical Dip stat deviations on spun dips
####
ObsDip_SDs<-as.numeric(masterdf$DipSDs)
ObsDip_SDs_conv=(ObsDip_SDs*SDSpunsDips)+meanSpunDips

plotdf<-data.frame(ObsDip_SDs_conv,SpunDips)

ggplot(plotdf,aes(x=SpunDips))+geom_density(size=1.5)+geom_boxplot(aes(ObsDip_SDs_conv),color='#BC3754')+theme_classic(base_size=23)+ylab('')+xlab('Dip Statistics: \u2207PG')+guides(y="none")+geom_vline(xintercept=c(ObsDip_SDs_conv))+geom_vline(xintercept = nineninePercentile,color='blue')

```

```{r}
RealDips=data.frame(masterdf$RealDips)
NullDips=data.frame(melt(NullDipsThresh))

ggplot(RealDips,aes(x=masterdf.RealDips))+geom_density(size=1.5,color='red')+theme_classic()+xlim(c(0,.04))

ggplot(NullDips,aes(x=value))+geom_density(size=1.5)+theme_classic()+xlim(c(0,.04))
```


```{r}
# individual level, set subj manually

SpunDips<-read.csv(paste0('Y:/results/PWs/Proced/',subj,'/',subj,'_SpunDips4.csv'),header=F)
ObsDip<-as.numeric(SpunDips[2,1001])
SpunDips<-as.numeric(SpunDips[2,1:1000])
plotdf<-data.frame(ObsDip,SpunDips)

ggplot(plotdf,aes(x=SpunDips))+geom_density(size=1.5)+geom_vline(xintercept = plotdf$ObsDip,size=2,color='#BC3754')+theme_classic(base_size=23)+ylab('')+xlab('Dip Statistics')+guides(y="none")+scale_x_continuous(limits =c(0,0.00823),breaks=c(0,0.004,0.008))

# saved out at 350 x 250

# try one as SD insead of raw
plotdf$sd<-(plotdf$SpunDips-mean(plotdf$SpunDips))/sd(plotdf$SpunDips)
plotdf$sd_o<-(plotdf$ObsDip-mean(plotdf$SpunDips))/sd(plotdf$SpunDips)

ggplot(plotdf,aes(sd))+geom_density(size=1.5)+geom_vline(xintercept = plotdf$sd_o,size=2,color='#BC3754')+theme_classic(base_size=23)+ylab('')+xlab('Dip Statistics')+guides(y="none")

########################33

nullDistrEx<-read.csv(paste0('Y:/results/PWs/Proced/',subj,'/',subj,'_SpunDistr1.csv'))
nullM<-melt(nullDistrEx)
hist(nullM$value)

# convert to histogram format, aligned with group-level plot
histoVers<-histc(nullM$value,edges=seq(0,180,10))
plotdataf<-data.frame(histoVers$cnt[1:18],seq(1,18))
# normalize to percentage, as in other
plotdataf$histoVers.cnt.1.18.<-plotdataf$histoVers.cnt.1.18./sum(plotdataf$histoVers.cnt.1.18.)

p<-ggplot(plotdataf,aes(x=seq.1..18.*10,y=histoVers.cnt.1.18.*100))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 26)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle(paste0('\u2207PG: Spun'))+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.05,.41))+ylab('count')+ylab('% of Propagations')+theme(plot.title= element_text(size=20, face="bold"), axis.title = element_blank(),axis.text = element_blank(),legend.title=element_blank(),legend.text=element_text(size=20),legend.position='none')+ylab('count')+ylab('% of Propagations')

# saved out at 300x300


```

```{r}
# repeat for temporal
SpunDips<-read.csv(paste0('Y:/results/PWs/Proced/',subj,'/',subj,'_ShufDips4.csv'),header=F)
ObsDip<-as.numeric(SpunDips[2,101])
SpunDips<-as.numeric(SpunDips[2,1:100])
plotdf<-data.frame(ObsDip,SpunDips)

ggplot(plotdf,aes(x=SpunDips))+geom_density(size=1.5)+geom_vline(xintercept = plotdf$ObsDip,size=2,color='#BC3754')+theme_classic(base_size=23)+ylab('')+xlab('Dip Statistics')+guides(y="none")+scale_x_continuous(limits =c(0,0.00823),breaks=c(0,0.004,0.008))

# saved out at 350 x 250

################################3
plotdf$sd<-(plotdf$SpunDips-mean(plotdf$SpunDips))/sd(plotdf$SpunDips)
plotdf$sd_o<-(plotdf$ObsDip-mean(plotdf$SpunDips))/sd(plotdf$SpunDips)
################################33
nullDistrEx<-read.csv(paste0('Y:/results/PWs/Proced/',subj,'/',subj,'_ShufDistr1.csv'))
nullM<-melt(nullDistrEx)
hist(nullM$value)

# convert to histogram format, aligned with group-level plot
histoVers<-histc(nullM$value,edges=seq(0,180,10))
plotdataf<-data.frame(histoVers$cnt[1:18],seq(1,18))
# normalize to percentage, as in other
plotdataf$histoVers.cnt.1.18.<-plotdataf$histoVers.cnt.1.18./sum(plotdataf$histoVers.cnt.1.18.)

p<-ggplot(plotdataf,aes(x=seq.1..18.*10,y=histoVers.cnt.1.18.*100))
p+geom_bar(stat='identity',color='black',aes(fill= ..x..),binwidth = 10)+xlab("Distance (Degrees)")+theme_classic(base_size = 26)+scale_x_continuous(limits=(c(0,190)))+scale_fill_gradientn("value",colors=c("blue","cyan","green","yellow","orange","red"))+ggtitle(paste0('\u2207PG: Spun'))+theme(legend.title=element_blank(),legend.text=element_text(size=20),legend.position=c(1.05,.41))+ylab('count')+ylab('% of Propagations')+theme(plot.title= element_text(size=20, face="bold"), axis.title = element_blank(),axis.text = element_blank(),legend.title=element_blank(),legend.text=element_text(size=20),legend.position='none')+ylab('count')+ylab('% of Propagations')
```