---
title: "PWsAnalysis"
author: "Adam"
date: "8/30/2021"
output: html_document
---

```{r}
library(mclust)
library(ggplot2)
library(ggpubr)
# read in master fc
mfc=read.csv('/cbica/projects/abcdfnets/results/masterfc.csv')
mfc$subjectkey<-gsub('sub-NDARINV','NDAR_INV',mfc$subjectkey)
gordon=read.delim('~/Downloads/Package_1191523/abcd_betnet02.txt')
gordon$rsfmri_c_ngd_dt_ngd_dla<-as.numeric(gordon$rsfmri_c_ngd_dt_ngd_dla)
df<-merge(gordon,mfc,by='subjectkey')
# just baseline
df<-subset(df,df$eventname=='baseline_year_1_arm_1')
```

```{r}
# very low motion subjects
#df$rsfmri_c_ngd_meanmotion<-as.numeric(df$rsfmri_c_ngd_meanmotion)
#lowMotSubjs<-df$subjectkey[df$rsfmri_c_ngd_meanmotion < 0.06]
## save out for aggregate group level lowmot script
#lowMotSubjs<-gsub('NDAR_INV','sub-NDARINV',lowMotSubjs)
##saveRDS(lowMotSubjs,'/cbica/projects/abcdfnets/dropbox/vLowMotSubjs.rds')
```

```{r}
# read in demographics
demo<-read.delim('~/Downloads/Package_1192012/abcd_lpds01.txt')
demo<-subset(demo,eventname=='baseline_year_1_arm_1')
demo2<-read.delim('~/Downloads/Package_1192704/pdem02.txt')
demo2<-subset(demo2,eventname=='baseline_year_1_arm_1')
demo<-merge(demo,demo2,by='subjectkey')
# read in cbcl
cbcl<-read.delim('~/Downloads/Package_1191879/abcd_cbcls01.txt')
cbcl<-subset(cbcl,eventname=='baseline_year_1_arm_1')
# read in nih TB
nihTB<-read.delim('~/Downloads/Package_1191879/abcd_tbss01.txt')
nihTB<-subset(nihTB,eventname=='baseline_year_1_arm_1')
# read in scanner info
scnerInf<-read.delim('~/Downloads/Package_1192010/abcd_mri01.txt')
scnerInf<-subset(scnerInf,eventname=='baseline_year_1_arm_1')
# read in fam info
famInf<-read.delim('~/Downloads/Package_1192820/acspsw03.txt')
famInf<-subset(famInf,eventname=='baseline_year_1_arm_1')

# merge
masterdf<-merge(demo,cbcl,by='subjectkey')
masterdf<-merge(masterdf,nihTB,by='subjectkey')
masterdf<-merge(masterdf,scnerInf,by='subjectkey')
masterdf<-merge(masterdf,famInf,by='subjectkey')
# merge w/ gordo and fc
masterdf<-merge(masterdf,df,by='subjectkey')

# load in subject-level waves
subjW<-readRDS('/cbica/projects/abcdfnets/results/Subject-level_waves')
subjW$subjectkey<-unlist(lapply(subjW$ID, function(x){
  strs<-strsplit(x,'/')[[1]]
  return(strs[7])
} ))
subjW$subjectkey<-gsub('sub-NDARINV','NDAR_INV',subjW$subjectkey)

#groupW<-readRDS('/cbica/projects/abcdfnets/results/restGroup-level_waves')

#groupW2<-readRDS('/cbica/projects/abcdfnets/results/restGroup-level_waves2')

# merge in
masterdf<-merge(masterdf,subjW,by='subjectkey')

# few variables remaining as char
masterdf$interview_age<-as.numeric(masterdf$interview_age.x)
masterdf$rsfmri_c_ngd_dt_ngd_dt<-as.numeric(masterdf$rsfmri_c_ngd_dt_ngd_dt)
masterdf$nihtbx_totalcomp_uncorrected<-as.numeric(masterdf$nihtbx_totalcomp_uncorrected)

# and exclusions not caught by 3165
rIi<-read.delim('~/Downloads/Package_1192010/abcd_imgincl01.txt')
rIi<-subset(rIi,eventname=='baseline_year_1_arm_1')
# get rid of duplicates
duplidf<-data.frame(rIi$subjectkey,rIi$imgincl_rsfmri_include)
colnames(duplidf)<-c('subjectkey','imgincl_rsfmri_include')
rIinoDup<-unique(duplidf)
masterdf<-merge(masterdf,rIinoDup,by='subjectkey')
paste0('subjs b4 rsfmri exclusion ',dim(masterdf)[1])
# exclude
masterdf<-masterdf[masterdf$imgincl_rsfmri_include==1,]
paste0('subjs after rsfmri exclusion ',dim(masterdf)[1])
# exclude one subject with a million trs (20 SD above mean)
masterdf<-masterdf[masterdf$TRs_r<8000,]
```

```{r}
#another misread variable
masterdf$rsfmri_c_ngd_meanmotion<-as.numeric(masterdf$rsfmri_c_ngd_meanmotion)
# data missingness
summary(masterdf$numW_r)
masterdf<-masterdf[!is.na(masterdf$numW_r),]
```

```{r}
# self-reported arousal
Arous<-read.delim('~/Downloads/Package_1192530/abcd_ypsq101.txt')
Arous<-subset(Arous,eventname=='baseline_year_1_arm_1')
masterdf<-merge(masterdf,Arous,by='subjectkey')
masterdf$RestRat<-masterdf$numTD_r/masterdf$numBU_r
#InfInd<-grep('Inf',masterdf$RestRat)
#masterdf<-masterdf[-c(InfInd),]
#task perf
#nBtp<-read.delim('~/Downloads/Package_1192187/abcd_mrinback02.txt')
#nBtp<-subset(nBtp,eventname=='baseline_year_1_arm_1')
#midtp<-read.delim('~/Downloads/Package_1192187/abcd_mid02.txt')
#midtp<-subset(midtp,eventname=='baseline_year_1_arm_1')
#masterdf<-merge(masterdf,midtp)
#masterdf$tfmri_mid_all_beh_lrwpfb_nt<-as.numeric(masterdf$tfmri_mid_all_beh_lrwpfb_nt)
#masterdf$tfmri_mid_all_beh_srwpfb_nt<-as.numeric(masterdf$tfmri_mid_all_beh_srwpfb_nt)
masterdf$interview_age<-as.numeric(masterdf$interview_age.x)
masterdf$cbcl_scr_syn_internal_r<-as.numeric(masterdf$cbcl_scr_syn_internal_r)
masterdf$cbcl_scr_syn_external_r<-as.numeric(masterdf$cbcl_scr_syn_external_r)
masterdf$postscan_sleepy_1<-as.numeric(masterdf$postscan_sleepy_1)
```

```{r}
# drop un specified family incomes
masterdf<-masterdf[masterdf$demo_comb_income_v2!='999',]
masterdf<-masterdf[masterdf$demo_comb_income_v2!='777',]
masterdf$demo_comb_income_v2<-as.numeric(masterdf$demo_comb_income_v2)
# and TR excl
masterdf<-masterdf[masterdf$TRs_r>900,]

# big linear models
InternalizingFull<-lmer(numBU_r~numW_r+interview_age+sex.x+TRs_r+(1|mri_info_deviceserialnumber:rel_family_id)+demo_comb_income_v2+rsfmri_c_ngd_meanmotion+rsfmri_c_ngd_dt_ngd_dla+cbcl_scr_syn_internal_r+demo_prnt_ed_v2+demo_prtnr_ed_v2+mri_info_manufacturer,data=masterdf)

InternalizingReduced<-lmer(numBU_r~numW_r+interview_age+sex.x+TRs_r+(1|mri_info_deviceserialnumber:rel_family_id)+demo_comb_income_v2+rsfmri_c_ngd_meanmotion+rsfmri_c_ngd_dt_ngd_dla+demo_prnt_ed_v2+demo_prtnr_ed_v2+mri_info_manufacturer,data=masterdf)

InternalizingLM<-lm(numBU_r~interview_age+sex.x+mri_info_deviceserialnumber+TRs_r+rsfmri_c_ngd_meanmotion+rsfmri_c_ngd_dt_ngd_dla+cbcl_scr_syn_internal_r+mri_info_manufacturer,data=masterdf)


```

```{r}
### plot DR2 with TD and BU
######## for dmn
# obtain PG values for each net
HierVec<-read.csv('/cbica/projects/abcdfnets/results/hierarchyVec.csv')
# get ordering for grayOrd plots
Hordering<-sort(HierVec$HierarchyVec,index.return=TRUE)
print(Hordering$ix)
# init vector
NetBs<-NULL
NetPs<-NULL
# highest is one (DM), lowest is 2 (Mot), 6 is lowest viz
for (i in 1:17){
  Network=i
  NetworkColname=paste0('X1_',i,'rest')
  Modformula=as.formula(paste0(NetworkColname,'~numTD_r+mri_info_deviceserialnumber+mri_info_manufacturer+rsfmri_c_ngd_meanmotion'))
  model<-lm(Modformula,data=masterdf)
  NetBs[i]<-summary(model)$coefficients['numTD_r','Estimate']
  NetPs[i]<-summary(model)$coefficients['numTD_r','Pr(>|t|)']
}

fdred<-p.adjust(NetPs,method='fdr')
sigBin<-fdred
sigBin[fdred<0.05]<-1
sigBin[fdred>0.05]<-0

# make dataframe out of hierarchy vector and B's and P's
DMNconDF<-data.frame(HierVec,NetBs,fdred,sigBin)


ggplot(DMNconDF,aes(x=HierarchyVec,y=NetBs))+geom_point(color=sigBin+1,size=3)+theme_classic(base_size=16)+ylab('Network-DMN Connectivity Association With number of Top-Down Waves')

######### for motor - BU
# init vector
NetBs<-NULL
NetPs<-NULL
# exceptionalism for network 1
model<-lm(X1_2rest~numBU_r+mri_info_deviceserialnumber+TRs_r+mri_info_manufacturer+rsfmri_c_ngd_meanmotion,data=masterdf)
NetBs[1]<-summary(model)$coefficients['numBU_r','Estimate']
NetPs[1]<-summary(model)$coefficients['numBU_r','Pr(>|t|)']
# highest is one (DM), lowest is 2 (Mot), 6 is lowest viz
for (i in 2:17){
  Network=i
  NetworkColname=paste0('X2_',i,'rest')
  Modformula=as.formula(paste0(NetworkColname,'~numBU_r+TRs_r+mri_info_deviceserialnumber+mri_info_manufacturer+rsfmri_c_ngd_meanmotion'))
  model<-lm(Modformula,data=masterdf)
  NetBs[i]<-summary(model)$coefficients['numBU_r','Estimate']
  NetPs[i]<-summary(model)$coefficients['numBU_r','Pr(>|t|)']
}

fdred<-p.adjust(NetPs,method='fdr')
sigBin<-fdred
sigBin[fdred<0.05]<-1
sigBin[fdred>0.05]<-0

# make dataframe out of hierarchy vector and B's and P's
MotconDF<-data.frame(HierVec,NetBs,fdred,sigBin)


ggplot(MotconDF,aes(x=HierarchyVec,y=NetBs))+geom_point(color=sigBin+1,size=3)+theme_classic(base_size=16)+ylab('Network-Motor Connectivity Association With number of Bottom-up Waves')

######## and for visual
# init vector
NetBs<-NULL
NetPs<-NULL

# split into before and after net 6
for (i in 1:5){
  Network=i
  NetworkColname=paste0('X',i,'_6rest')
  Modformula=as.formula(paste0(NetworkColname,'~numBU_r+TRs_r+mri_info_deviceserialnumber+mri_info_manufacturer+rsfmri_c_ngd_meanmotion'))
  model<-lm(Modformula,data=masterdf)
  NetBs[i]<-summary(model)$coefficients['numBU_r','Estimate']
  NetPs[i]<-summary(model)$coefficients['numBU_r','Pr(>|t|)']
}

# highest is one (DM), lowest is 2 (Mot), 6 is lowest viz
for (i in 6:17){
  Network=i
  NetworkColname=paste0('X6_',i,'rest')
  Modformula=as.formula(paste0(NetworkColname,'~numBU_r+TRs_r+mri_info_deviceserialnumber+mri_info_manufacturer+rsfmri_c_ngd_meanmotion'))
  model<-lm(Modformula,data=masterdf)
  NetBs[i]<-summary(model)$coefficients['numBU_r','Estimate']
  NetPs[i]<-summary(model)$coefficients['numBU_r','Pr(>|t|)']
}

fdred<-p.adjust(NetPs,method='fdr')
sigBin<-fdred
sigBin[fdred<0.05]<-1
sigBin[fdred>0.05]<-0

# make dataframe out of hierarchy vector and B's and P's
VisconDF<-data.frame(HierVec,NetBs,fdred,sigBin)


ggplot(VisconDF,aes(x=HierarchyVec,y=NetBs))+geom_point(color=sigBin+1,size=3)+theme_classic(base_size=16)+ylab('Network-Visual Connectivity Association With number of Bottom-Up Waves')
```

```{r}
# low motion group level waves
rest<-readRDS('/cbica/projects/abcdfnets/results/restGroup-level_waves')
rest_gPG<-readRDS('/cbica/projects/abcdfnets/results/restGroup-level_waves_gPG')

hist(rest$PGCor,breaks = seq(-1,1,by=.1))
hist(rest_gPG$PGCor,breaks = seq(-1,1,by=.1))

# create random correlation null for comparison
corvec<-seq(1:length(rest$PGCor))
for (i in 1:length(rest$PGCor)){
  vector1<-sample(seq(1:70), size = 70, replace = FALSE)
  vector2<-sample(seq(1:70), size = 70, replace = FALSE)
  corvec[i]=cor.test(vector1,vector2,method='spearman')$estimate
}
hist(corvec,breaks = seq(-1,1,by=.1))
```


```{r}
nbG<-readRDS('/cbica/projects/abcdfnets/results/nbackGroup-level_waves')
nbG_gPG<-readRDS('/cbica/projects/abcdfnets/results/nbackGroup-level_waves_gPG')
midG<-readRDS('/cbica/projects/abcdfnets/results/MIDGroup-level_waves')
midG_gPG<-readRDS('/cbica/projects/abcdfnets/results/MIDGroup-level_waves_gPG')
sstG<-readRDS('/cbica/projects/abcdfnets/results/SSTGroup-level_waves')
sstG_gPG<-readRDS('/cbica/projects/abcdfnets/results/SSTGroup-level_waves_gPG')

hist(restG_gPG$PGCor,breaks = seq(-1,1,by=.1))
hist(midG$PGCor,breaks = seq(-1,1,by=.1))

rest_GM<-Mclust(na.omit(rest$PGCor),G=3)
restG_gPG_GM<-Mclust(na.omit(restG_gPG$PGCor),G=3)
midG_GM<-Mclust(na.omit(midG$PGCor),G=3)

hist(nbG$PGCor,breaks = seq(-1,1,by=.1))
hist(midG$PGCor,breaks = seq(-1,1,by=.1))

hist(restG$TempSpan*.8,breaks = seq(0,60,by=5))
hist(restG_gPG$TempSpan*.8,breaks = seq(0,60,by=5))
hist(nbG$TempSpan*.8,breaks = seq(0,90,by=5))
hist(midG$TempSpan*.8,breaks = seq(0,90,by=5))

restG_6GM<-Mclust(restG_6$PGCor,G=3)
restG_GM66<-Mclust(restG_66$PGCor,G=3)


nbG_GM<-Mclust(nbG$PGCor,G=3)
midG_GM<-Mclust(midG$PGCor,G=3)
sstG_GM<-Mclust(sstG$PGCor,G=3)
```