---
title: "Untitled"
author: "Adam"
date: "10/6/2021"
output: html_document
---

```{r}
library(ggplot2)
library(reshape2)

### subject-level PW measures

# read in grad positioning of nets
NetPosish=read.delim('/cbica/projects/abcdfnets/results/NetsInGrads.csv',header=T,sep=',')

# sep out grad1 and grad2 vals
grad1vals=NetPosish[,1:17]
grad2vals=NetPosish[,18:34]

# melt em
grad1M=melt(grad1vals)
grad2M=melt(grad2vals)

# relabel
colnames(grad1M)<-c('Network','PG1')
colnames(grad2M)<-c('NetworkPlus17','PG2')
# combine
plotdf<-cbind(grad1M,grad2M)

# color vector
colors=c('red','blue','orange','blue','green','purple','pink','red','pink','purple','blue','red','blue','green','orange','darkslateblue','orange')

ggplot(data=plotdf,aes(x=PG1,y=PG2,color=Network))+geom_point(size=2)+scale_color_manual(values=colors)+theme_classic()
```

```{r}
# examples subj
testSubj=read.delim('/cbica/projects/abcdfnets/results/test_rest_BinWisePhase.csv',header=F,sep=' ')

# normative phase offset
colMeans(abs(testSubj),na.rm=T)

# tranpose
testSubj=t(testSubj)

instance1=na.omit(cbind(abs(testSubj[,1]),seq(1,24)))

instance2=na.omit(cbind(abs(testSubj[,2]),seq(1,24)))

instance3=na.omit(cbind(abs(testSubj[,3]),seq(1,24)))

# corVec
corVec=NULL
for (i in 1:15){
  plot(abs(testSubj[,i]))
  instance=na.omit(cbind(abs(testSubj[,i]),seq(1,24)))
  cor=cor.test(instance[,1],instance[,2])
  corVec[i]=cor$estimate
}
```

```{r}
library(reshape2)
library(ggplot2)
df<-read.csv('/cbica/projects/abcdfnets/results/rest_BinWiseMeanPhase.csv')
df=df[-c(1)]
PhaseOffsets=melt(df,id='X1')
ggplot(data=PhaseOffsets,aes(x=variable,y=value,group=X1,color=X1))+geom_line(alpha=.5)+scale_color_gradientn(colours = rainbow(5))

ggplot(data=PhaseOffsets,aes(x=variable,y=value,group=X1,color=X1))+geom_smooth(method='gam',alpha=.2,se=F)+scale_color_gradientn(colours = rainbow(5))+theme_classic()+xlab('PG Bin')+ylab('Phase Offset from top PG bin')

### convert into single, subject-level measure
corVec=NULL
cbound=NULL
# useful variable names only
sequence=seq(1,24)
for (i in 1:dim(df)[1]){
  cbound=cbind(t(df[i,2:25]),sequence)
  corVec[i]=cor.test(cbound[,1],cbound[,2])$estimate
}
```

```{r}
dfM<-read.csv('/cbica/projects/abcdfnets/results/rest_BinWiseMeanMag.csv')
dfM=dfM[-c(1)]
Magnitudes=melt(dfM,id='X1')
ggplot(data=Magnitudes,aes(x=variable,y=value,group=X1,color=X1))+geom_line(alpha=.5)+scale_color_gradientn(colours = rainbow(5))+theme_classic()+xlab('PG Bin')+ylab('Mean Magnitude of Wave Peak')

ggplot(data=Magnitudes,aes(x=variable,y=value,group=X1,color=X1,alpha=.3))+geom_smooth(method='gam',alpha=.2,se=F)+scale_color_gradientn(colours = rainbow(5))+theme_classic()+xlab('PG Bin')+ylab('Mean Magnitude of Wave Peak')

### convert into single, subject-level measure
#MagVec=NULL
#for (i in 1:dim(df)[1]){
#  MagVec[i]=mean(t(Magnitudes[i,2:26]))
#}

```

```{r}
library(shapes)
# 24 units for y-axis
dummyData=rep(NaN,100*2*24)
# intialize shape 3d matrix
shapeArray<-array(dummyData,c(24,2,100))
# populate shape array
for (s in 1:100){
  # fill in x (pg bin)
  pgbins=seq(1,24)
  pgbins=pgbins
  shapeArray[1:24,1,s]=pgbins
  # fill in y (phase offset)
  phaseOffset=unlist(df[s,2:25])
  # scale it to the same size as phase offsets
  phaseOffset=(phaseOffset*25)
  # convert to smooth
  iterdf=data.frame(phaseOffset,pgbins)
  phaseOffsetSmooth=gam(phaseOffset~s(pgbins,k=5),data=iterdf)$fitted.values
  shapeArray[1:24,2,s]=phaseOffsetSmooth
  #plot
  plot(phaseOffsetSmooth)
}

procrust<-procGPA(shapeArray)
scores<-procrust$scores
```

```{r}
# now for magnitude
dummyData=rep(NaN,100*2*24)
# intialize shape 3d matrix
shapeArray<-array(dummyData,c(24,2,100))
# populate shape array
for (s in 1:100){
  # fill in x (pg bin)
  pgbins=seq(1,24)
  pgbins=pgbins
  shapeArray[1:24,1,s]=pgbins
  # fill in y (phase offset)
  Mags=unlist(dfM[s,2:25])
  # scale it to the same size as phase offsets
  Mags=(Mags*25)
  # convert to smooth
  iterdf=data.frame(Mags,pgbins)
  phaseOffsetSmooth=gam(Mags~s(pgbins,k=5),data=iterdf)$fitted.values
  shapeArray[1:24,2,s]=phaseOffsetSmooth
  #plot
  plot(phaseOffsetSmooth)
}

procrust<-procGPA(shapeArray)
scores<-procrust$scores
```

```{r}
# test subj
spunMag<-read.csv('/cbica/projects/abcdfnets/dropbox/test_restMagPGBbinSpin.csv',header=F)
spunPh<-read.csv('/cbica/projects/abcdfnets/dropbox/test_restPhasePGBbinSpin.csv',header=F)
spunDur<-read.csv('/cbica/projects/abcdfnets/dropbox/test_AvgDurSpin.csv',header=F)

# observed
ggplot(data=PhaseOffsets[PhaseOffsets$X1==31,],aes(x=variable,y=value,group=X1))+geom_line(alpha=.5)+theme_classic()
ggplot(data=Magnitudes[Magnitudes$X1==31,],aes(x=variable,y=value,group=X1))+geom_line(alpha=.5)+ylim(0,.7)+theme_classic()

# nulls
spunPh$group<-seq(1:100)
spunMag$group<-seq(1:100)

# tag on observed for comparison
spunPh[101,1:24]<-df[1,2:25]
spunPh[101,25]<-101
spunMag[101,1:25]<-dfM[1,2:26]
spunMag[101,26]<-101

# only plotting 10 nulls at a time to make sense of it
spunPhM=melt(spunPh[100:101,],id='group')
spunMagM=melt(spunMag[1:101,],id='group')

#phase nulls
ggplot(data=spunPhM,aes(x=variable,y=value,group=group,color=group))+geom_line(alpha=.7)+scale_color_gradientn(colours = rainbow(5))+theme_classic()+ylab('Phase Offset')+xlab('PG Bin')

# mag nulls
ggplot(data=spunMagM,aes(x=variable,y=value,group=group,color=group))+geom_line(alpha=.7)+scale_color_gradientn(colours = rainbow(5))+ylim(0,.7)+theme_classic()+ylab('Magnitude')+xlab('PG Bin')

# test phase * pg cor vs. nulls
PhPGcorvec<-NULL
for (i in 1:101){
  PhPGcorvec[i]<-cor.test(seq(1:24),unlist(spunPh[i,1:24]))$estimate
}
```